import React from "react";
import BlankHeader from "../../blankheader";

function Policy() {
  return (
    <div style={{backgroundColor: "#fff"}} className="py-3">
      <BlankHeader />
      <div className="container-fluid">
        <div className="outerpadding">
          <div className="content-block content-block--center content-block--snippet" style={{textAlign:"justify"}}>
            <h1 className="title-wrap__title no-letter-spacing m-0" style={{textAlign: "justify"}}>Privacy Policy</h1>
            <p style={{textAlign: "justify",margin:"0"}}>&nbsp;</p>
            <p style={{textAlign: "justify"}}>
              This privacy policy is applicable to the website 
              <a href="http://www.adityabirlasunlifeinsurance.com/"> www.adityabirlasunlifeinsurance.com</a>
            </p>
            <p style={{textAlign: "justify"}}>PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY USING ANY OF THE SERVICES, YOU REPRESENT THAT YOU HAVE READ AND UNDERSTAND THE TERMS AND CONDITIONS OF USAGE (hereinafter called as 'Terms of Use'), WHICH INCLUDES THIS PRIVACY POLICY, AND YOU AGREE TO BE BOUND BY ALL ITS TERMS. TERMS NOT DEFINED IN THIS PRIVACY POLICY HAVE THE MEANING DESCRIBED IN THE TERMS OF USE.</p>
            <h2 style={{textAlign: "justify"}}><strong>Personally Identifiable Information:</strong></h2>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com is committed to protecting your privacy and working towards offering you a powerful, safe, online experience. To avail some of the services offered by Www.adityabirlasunlifeinsurance.com, you need to sign up by giving simple details that personally identify you. Www.adityabirlasunlifeinsurance.com needs this minimal information to operate the online services. Www.adityabirlasunlifeinsurance.com encourages you to update this information as and when there are any changes. When you do this through easily navigable clicks, you help us stay in touch with you always.</p>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com does not collect personal information about individuals except when such individuals specifically provide such information on a voluntary basis. This can be in several ways including for example, through registration for contests, the registration process for subscription sites or services and in connection with content submissions, community postings (e.g., message boards), suggestions, and voting/polling activities. Personal information of individual users of www.adityabirlasunlifeinsurance.com will not be sold or otherwise transferred to unaffiliated third parties unless otherwise stated at the time of collection or without the approval of the user as the case may be. Www.adityabirlasunlifeinsurance.com uses the help of Internet Protocol ("IP") addresses to diagnose any problems with its server and to administer the web site www.adityabirlasunlifeinsurance.com, including by blocking certain addresses that it feels are inappropriately using its website. IP addresses are used to gather broad demographics information, such as browser types, visitor's country, visiting frequency, operating systems, etc.</p>
            <h2 style={{textAlign: "justify"}}><strong>Cookies:</strong></h2>
            <p style={{textAlign: "justify"}}>Users are also made aware that certain information and data may be automatically collected through the standard operation of www.adityabirlasunlifeinsurance.com's internet servers or through the use of "cookies." "Cookies" is a term generally used for small text files a web site can use to recognize repeat users, facilitate the user's ongoing access to and use of the site, allow a site to track usage behavior and compile aggregate data that will allow content improvements and targeted advertising etc. Cookies themselves do not personally identify you, but they do identify your computer Generally, cookies work by assigning a unique number to the user computer that has no meaning outside the assigning site.<strong>You have the option to reset your browser to control cookies; however, some of the services offered by the Website services may not function properly if cookies are refused.</strong></p>
            <h2 style={{textAlign: "justify"}}><strong>Sharing of Information:</strong></h2>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com treats your personal information or your use of the Service as private and confidential and does not check, edit, or reveal it to any third parties except where it believes in good faith, such action is necessary to comply with the applicable legal and regulatory processes, or to protect and defend the rights of other users or to enforce the terms of service which are binding on all the users of Www.adityabirlasunlifeinsurance.com. Www.adityabirlasunlifeinsurance.com may collect unnamed statistics, which does not personally identify you. www.adityabirlasunlifeinsurance.com reserves the right to perform statistical analyses of user behavior and characteristics in order to measure interest in Aditya Birla Sun Life Insurance products. Parents are requested to ensure that personal information is not provided by minors on www.adityabirlasunlifeinsurance.com website. However, this does not intend to prohibit information on minors and children being provided by the parents with respect to any product or service offered by www.adityabirlasunlifeinsurance.com or any other third party permitted to offer any product or service on its site, which are beneficial to or are designed for the benefit of children and minors.</p>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com notifies that the information you provide to Www.adityabirlasunlifeinsurance.com may be stored in a country other than where you reside.</p>
            <h2 style={{textAlign: "justify"}}><strong>Communication:</strong></h2>
            <p style={{textAlign: "justify"}}>Except where specifically agreed or necessary for operational or regulatory reasons, Www.adityabirlasunlifeinsurance.com will not send you any unsolicited information. However, to help you to take full advantage of Www.adityabirlasunlifeinsurance.com, messages relating to the Www.adityabirlasunlifeinsurance.com products/services and/or changes, additions and improvements to the products/services offered may be sent to you. Further at such points of collection, the user will have the opportunity to indicate whether he or she would like to "opt out" of receiving promotional and/or marketing information about other products, services and offerings from www.adityabirlasunlifeinsurance.com and/or any third parties etc. If the user does not opt out, www.adityabirlasunlifeinsurance.com may use any email addresses of users to send occasional emails pertaining to the said information. The user can nevertheless unsubscribe from receipt of such emails by following instructions therein or by communicating accordingly to www.adityabirlasunlifeinsurance.com.</p>
            <h2 style={{textAlign: "justify"}}><strong>Third Party Offers:</strong></h2>
            <p style={{textAlign: "justify"}}>Also, users should be aware that www.adityabirlasunlifeinsurance.com may sometimes permit third parties to offer subscription and/or registration-based services through its site. www.adityabirlasunlifeinsurance.com is not responsible for any actions or policies of such third parties and users should check the applicable privacy policy of such party when providing personally identifiable information. Further, www.adityabirlasunlifeinsurance.com will not be responsible if the users do no get the benefits announced if any, by the third parties permitted to offer subscription and registration based services on its site.</p>
            <h2 style={{textAlign: "justify"}}><strong>EXCLUSION:</strong></h2>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com believes in promoting amity among users to promote collaboration and free exchange of ideas. Www.adityabirlasunlifeinsurance.com may provide specific services to users to post messages, e-mails, information, participate in chat sessions, news groups and other affinity group activities on the site and off the site. During such activities, you may provide your personal information beyond what has been given in your personal profile. Www.adityabirlasunlifeinsurance.com's Privacy Policy excludes information transmitted through these activities. While Www.adityabirlasunlifeinsurance.com encourages you to actively participate in such activities, it advises you to be careful in sharing your personal information and respect the privacy of its other users.</p>
            <p style={{textAlign: "justify"}}><strong>E-mail messages sent to Aditya Birla Sun Life Insurance over the Internet cannot be guaranteed to be completely secure. The integrity of such messages cannot be guaranteed on the Internet and ABSLI will not be responsible for any damages incurred by users due to messages sent or received by them to and from ABSLI.</strong></p>
            <h2 style={{textAlign: "justify"}}><strong>Policy Changes:</strong></h2>
            <p style={{textAlign: "justify"}}>Www.adityabirlasunlifeinsurance.com reserves the right to change this policy at any time. If www.adityabirlasunlifeinsurance.com decides to change this policy, such changes will be posted on this page as soon as possible. Users may note that this Privacy Policy itself and any such change of policy will be may be effective from the date announced by www.adityabirlasunlifeinsurance.com and not from the date of posting on the site.</p>
            <h2 style={{textAlign: "justify"}}><strong>Contact us:</strong></h2>
            <p style={{textAlign: "justify"}}>This statement and the policies outlined herein are not intended to and do not create any contractual or other legal rights in favor of any user or viewer of www.adityabirlasunlifeinsurance.com or on behalf of any other party.</p>
            <p style={{textAlign: "justify"}} className="mb-0">However, users and viewers are informed that by using the web site <a href="http://www.adityabirlasunlifeinsurance.com/">www.adityabirlasunlifeinsurance.com</a>, they are deemed to have consented to the collection and use of information by adityabirlacapital.com as stated above.The web site <a href="http://www.adityabirlasunlifeinsurance.com/">www.adityabirlasunlifeinsurance.com</a> is maintained by Aditya Birla Sun Life Insurance Company Limited having its registered office at Aditya Birla Sun Life Insurance Company Limited, One Indiabulls Centre, Tower 1, 16th Floor, Jupiter Mill Compound, 841, Senapati Bapat Marg, Elphinstone Road Mumbai - 400013, Corporate Identity Number: U99999MH2000PLC128110, who can be reached by email at <a href="mailto:care.lifeinsurance@adityabirlacapital.com">care.lifeinsurance@adityabirlacapital.com</a> <strong>Or call us on 1-800-270-7000 (Toll Free) between 9 am to 9 pm, Monday to Saturday.</strong></p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Policy;
